# Generated by Django 3.1 on 2021-02-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='districts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
