# Generated by Django 3.1.5 on 2021-02-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0002_region_districts'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='School Name')),
                ('logo', models.ImageField(upload_to='school_logos/')),
                ('gender', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('co-ed/boys and girls', 'co-ed/boys and girls')], max_length=100)),
                ('accomodation_type', models.CharField(choices=[('Boarding/Hostel', 'Boarding/Hostel'), ('Day', 'Day')], max_length=100)),
                ('class_size', models.CharField(choices=[('40 students in class', '40 students in class'), ('40+ students in class', '40+ students in class')], max_length=100)),
                ('school_type', models.CharField(choices=[('General', 'General'), ('Seminary', 'Seminary'), ('Christian Seminary', 'Christian Seminary'), ('Islamic Seminary', 'Islamic Seminary')], max_length=100)),
                ('school_multicultural', models.CharField(choices=[('Yes', 'Yes'), ('Not necessary', 'Not necessary')], max_length=100)),
                ('school_location', models.CharField(choices=[('Big cities', 'Big cities'), ('Mid towns', 'Mid towns'), ('villages areas', 'village areas')], max_length=100)),
                ('curricular_system', models.CharField(choices=[('NECTA', 'NECTA'), ('International curriculars', 'International curriculars')], max_length=100)),
                ('school_subjects', models.CharField(choices=[('Business-based subjects', 'Business-based subjects'), ('Science-based subjects', 'Science-based subjects'), ('Nutrition', 'Nutrition'), ('Agriculture', 'Agriculture'), ('Computer science', 'Computer science'), ('Fine Art', 'Fine Art'), ('Physical/Sports education', 'Physical/Sports education'), ('Music', 'Music')], max_length=100)),
                ('olevel_exam_results_review', models.CharField(choices=[('1 Year', '1 Year'), ('3 Year', '3 Year'), ('5 year', '5 Year')], max_length=100)),
                ('subject_combination', models.CharField(choices=[('CBA', 'CBA'), ('CBN', 'CBN'), ('CBG', 'CBG'), ('ECA', 'ECA'), ('EGM', 'EGM'), ('HGE', 'HGE'), ('HGK', 'HGK'), ('HGL', 'HGL'), ('HKL', 'HKL'), ('KLA', 'KLA'), ('KLF', 'KLF'), ('PCB', 'PCB'), ('PCM', 'PCM'), ('PGM', 'PGM'), ('ARB', 'ARB'), ('Computer science', 'Computer science'), ('Divinity', 'Divinity'), ('Islamic', 'Islamic')], max_length=100)),
                ('alevel_exam_results_review', models.CharField(choices=[('1 Year', '1 Year'), ('3 Year', '3 Year'), ('5 year', '5 Year')], max_length=100)),
                ('minimum_tution_fee', models.DecimalField(decimal_places=0, max_digits=9)),
                ('maximum_tution_fee', models.DecimalField(decimal_places=0, max_digits=9)),
                ('no_fee', models.BooleanField(default=False, verbose_name='School has scholarship or supported by charity (no-fee)')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.district')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.region')),
            ],
        ),
    ]
