# Generated by Django 3.1.5 on 2021-02-16 12:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210216_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(upload_to='school_logos/', verbose_name='Upload School Logo'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Business-based subjects', 'Business-based subjects'), ('Science-based subjects', 'Science-based subjects'), ('Nutrition', 'Nutrition'), ('Agriculture', 'Agriculture'), ('Computer science', 'Computer science'), ('Fine Art', 'Fine Art'), ('Physical/Sports education', 'Physical/Sports education'), ('Music', 'Music')], max_length=100),
        ),
    ]
