# Generated by Django 3.1.5 on 2021-02-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210216_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_subjects',
            field=models.CharField(choices=[('Business-based subjects', 'Business-based subjects'), ('Science-based subjects', 'Science-based subjects'), ('Nutrition', 'Nutrition'), ('Agriculture', 'Agriculture'), ('Computer science', 'Computer science'), ('Fine Art', 'Fine Art'), ('Physical/Sports education', 'Physical/Sports education'), ('Music', 'Music')], max_length=100),
        ),
    ]
