# Generated by Django 3.1.5 on 2021-02-16 13:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210216_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Business-based subjects', 'Business-based subjects'), ('Science-based subjects', 'Science-based subjects'), ('Nutrition', 'Nutrition'), ('Agriculture', 'Agriculture'), ('Computer science', 'Computer science'), ('Fine Art', 'Fine Art'), ('Physical/Sports education', 'Physical/Sports education'), ('Music', 'Music')], max_length=100),
        ),
    ]
