# Generated by Django 3.1.5 on 2021-02-16 13:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210216_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='subject_combination',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CBA', 'CBA'), ('CBN', 'CBN'), ('CBG', 'CBG'), ('ECA', 'ECA'), ('EGM', 'EGM'), ('HGE', 'HGE'), ('HGK', 'HGK'), ('HGL', 'HGL'), ('HKL', 'HKL'), ('KLA', 'KLA'), ('KLF', 'KLF'), ('PCB', 'PCB'), ('PCM', 'PCM'), ('PGM', 'PGM'), ('ARB', 'ARB'), ('Computer science', 'Computer science'), ('Divinity', 'Divinity'), ('Islamic', 'Islamic')], max_length=100),
        ),
    ]
