# Generated by Django 3.1.5 on 2021-02-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210216_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='no_fee',
            field=models.BooleanField(default=False, verbose_name='School has scholarship or supported by charity (no-fee)?'),
        ),
    ]
