# Generated by Django 3.1.5 on 2021-02-17 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20210216_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='accomodation_type',
            field=models.CharField(choices=[('', 'select'), ('Boarding/Hostel', 'Boarding/Hostel'), ('Day', 'Day')], max_length=100, verbose_name='Accomodation Type'),
        ),
        migrations.AlterField(
            model_name='school',
            name='alevel_exam_results_review',
            field=models.CharField(blank=True, choices=[('', 'select'), ('1 Year', '1 Year'), ('3 Year', '3 Year'), ('5 year', '5 Year')], max_length=100, null=True, verbose_name="A'level Exams Results Review"),
        ),
        migrations.AlterField(
            model_name='school',
            name='class_size',
            field=models.CharField(choices=[('', 'select'), ('40 students in class', '40 students in class'), ('40+ students in class', '40+ students in class')], max_length=100, verbose_name='What is class size'),
        ),
        migrations.AlterField(
            model_name='school',
            name='curricular_system',
            field=models.CharField(choices=[('', 'select'), ('NECTA', 'NECTA'), ('International curriculars', 'International curriculars')], max_length=100, verbose_name='What is curricular system use?'),
        ),
        migrations.AlterField(
            model_name='school',
            name='gender',
            field=models.CharField(choices=[('', 'select'), ('Boys', 'Boys'), ('Girls', 'Girls'), ('co-ed/boys and girls', 'co-ed/boys and girls')], max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='maximum_tution_fee',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Maximum Tution Fee per Year'),
        ),
        migrations.AlterField(
            model_name='school',
            name='minimum_tution_fee',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Minimum Tution Fee per Year'),
        ),
        migrations.AlterField(
            model_name='school',
            name='olevel_exam_results_review',
            field=models.CharField(blank=True, choices=[('', 'select'), ('1 Year', '1 Year'), ('3 Year', '3 Year'), ('5 year', '5 Year')], max_length=100, null=True, verbose_name="O'level Exams Results Review"),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_location',
            field=models.CharField(choices=[('', 'select'), ('Big cities', 'Big cities'), ('Mid towns', 'Mid towns'), ('villages areas', 'village areas')], max_length=100, verbose_name='Where school located?'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_multicultural',
            field=models.CharField(choices=[('', 'select'), ('Yes', 'Yes'), ('Not necessary', 'Not necessary')], max_length=100, verbose_name='Is school has multicultural'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('', 'select'), ('General', 'General'), ('Seminary', 'Seminary'), ('Christian Seminary', 'Christian Seminary'), ('Islamic Seminary', 'Islamic Seminary')], max_length=100, verbose_name='What is School Type'),
        ),
        migrations.CreateModel(
            name='SchoolExamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('division_one', models.PositiveSmallIntegerField()),
                ('division_two', models.PositiveSmallIntegerField()),
                ('division_three', models.PositiveSmallIntegerField()),
                ('division_four', models.PositiveSmallIntegerField()),
                ('division_zero', models.PositiveSmallIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.school')),
            ],
        ),
    ]
