# Generated by Django 3.1.5 on 2021-02-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210218_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='maximum_tution_fee',
        ),
        migrations.RemoveField(
            model_name='school',
            name='minimum_tution_fee',
        ),
        migrations.AddField(
            model_name='school',
            name='average_tution_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Average Tution Fee per Year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='ownership',
            field=models.CharField(choices=[('', 'select'), ('General', 'General'), ('Christian Seminary', 'Christian Seminary'), ('Islamic Seminary', 'Islamic Seminary')], max_length=100, verbose_name='What is School Type'),
        ),
    ]
