# Generated by Django 3.1.5 on 2021-02-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210226_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_subjects',
        ),
        migrations.AddField(
            model_name='school',
            name='school_subjects',
            field=models.ManyToManyField(to='main.SchoolSubject'),
        ),
    ]
