# Generated by Django 3.1.5 on 2021-02-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210226_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolexamresult',
            name='dv0T',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolexamresult',
            name='dv1T',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolexamresult',
            name='dv2T',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolexamresult',
            name='dv3T',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolexamresult',
            name='dv4T',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolexamresult',
            name='division_four',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='schoolexamresult',
            name='division_one',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='schoolexamresult',
            name='division_three',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='schoolexamresult',
            name='division_two',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='schoolexamresult',
            name='division_zero',
            field=models.PositiveIntegerField(),
        ),
    ]
