# Generated by Django 3.1.5 on 2021-02-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210227_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolexamresult',
            name='dv0P',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolexamresult',
            name='dv1P',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolexamresult',
            name='dv2P',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolexamresult',
            name='dv3P',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolexamresult',
            name='dv4P',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
