# Generated by Django 3.1.5 on 2021-02-27 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210227_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alevelexamresult',
            name='dv0P',
        ),
        migrations.RemoveField(
            model_name='alevelexamresult',
            name='dv0T',
        ),
        migrations.RemoveField(
            model_name='alevelexamresult',
            name='dv1P',
        ),
        migrations.RemoveField(
            model_name='alevelexamresult',
            name='dv1T',
        ),
        migrations.RemoveField(
            model_name='alevelexamresult',
            name='dv2P',
        ),
        migrations.RemoveField(
            model_name='alevelexamresult',
            name='dv2T',
        ),
        migrations.RemoveField(
            model_name='alevelexamresult',
            name='dv3P',
        ),
        migrations.RemoveField(
            model_name='alevelexamresult',
            name='dv3T',
        ),
        migrations.RemoveField(
            model_name='alevelexamresult',
            name='dv4P',
        ),
        migrations.RemoveField(
            model_name='alevelexamresult',
            name='dv4T',
        ),
        migrations.RemoveField(
            model_name='alevelexamresult',
            name='total_point',
        ),
        migrations.RemoveField(
            model_name='olevelexamresult',
            name='dv0P',
        ),
        migrations.RemoveField(
            model_name='olevelexamresult',
            name='dv0T',
        ),
        migrations.RemoveField(
            model_name='olevelexamresult',
            name='dv1P',
        ),
        migrations.RemoveField(
            model_name='olevelexamresult',
            name='dv1T',
        ),
        migrations.RemoveField(
            model_name='olevelexamresult',
            name='dv2P',
        ),
        migrations.RemoveField(
            model_name='olevelexamresult',
            name='dv2T',
        ),
        migrations.RemoveField(
            model_name='olevelexamresult',
            name='dv3P',
        ),
        migrations.RemoveField(
            model_name='olevelexamresult',
            name='dv3T',
        ),
        migrations.RemoveField(
            model_name='olevelexamresult',
            name='dv4P',
        ),
        migrations.RemoveField(
            model_name='olevelexamresult',
            name='dv4T',
        ),
        migrations.RemoveField(
            model_name='olevelexamresult',
            name='total_point',
        ),
        migrations.CreateModel(
            name='OlevelExamRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('dv1T', models.PositiveIntegerField(blank=True, null=True)),
                ('dv2T', models.PositiveIntegerField(blank=True, null=True)),
                ('dv3T', models.PositiveIntegerField(blank=True, null=True)),
                ('dv4T', models.PositiveIntegerField(blank=True, null=True)),
                ('dv0T', models.PositiveIntegerField(blank=True, null=True)),
                ('dv1P', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dv2P', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dv3P', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dv4P', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dv0P', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_point', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.school')),
            ],
        ),
        migrations.CreateModel(
            name='AlevelExamRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('dv1T', models.PositiveIntegerField(blank=True, null=True)),
                ('dv2T', models.PositiveIntegerField(blank=True, null=True)),
                ('dv3T', models.PositiveIntegerField(blank=True, null=True)),
                ('dv4T', models.PositiveIntegerField(blank=True, null=True)),
                ('dv0T', models.PositiveIntegerField(blank=True, null=True)),
                ('dv1P', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dv2P', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dv3P', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dv4P', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dv0P', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_point', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.school')),
            ],
        ),
    ]
