# Generated by Django 3.1.5 on 2021-02-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210227_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='classe',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Form:'),
            preserve_default=False,
        ),
    ]
