# Generated by Django 3.1.5 on 2021-02-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_examresult_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrank',
            name='classe',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
