# Generated by Django 3.1.5 on 2021-04-18 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_region_districts'),
        ('main', '0027_auto_20210418_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.district'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.region'),
        ),
    ]
