# Generated by Django 3.1.5 on 2021-04-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210418_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchresult',
            name='school_subjects',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='school_subjects',
            field=models.ManyToManyField(blank=True, to='main.SchoolSubject'),
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='subject_combination',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='subject_combination',
            field=models.ManyToManyField(blank=True, to='main.SubjectCombination'),
        ),
    ]
