# Generated by Django 3.1.5 on 2021-04-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210418_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchresult',
            name='school_subjects',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='school_subjects',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='subject_combination',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='subject_combination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
