# Generated by Django 3.1.5 on 2021-04-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210418_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='fee_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='fee_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
