# Generated by Django 3.1.5 on 2021-04-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210418_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='school',
            field=models.ManyToManyField(blank=True, to='main.School'),
        ),
    ]
