# Generated by Django 3.1.5 on 2021-04-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210422_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='school',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='search',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
