# Generated by Django 3.1.5 on 2021-06-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20210422_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='search_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
